name: "Auto Label PRs & Issues"

on:
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label PRs/Issues
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GIT_TOKEN }}

