array types:
  - 'array types'

Benchmarks:
  - 'BENCH'

Build issues:
  - 'BLD'

CI:
  - 'CI'

defect:
  - '(BUG|FIX)'

deprecated:
  - 'DEP'

Documentation:
  - 'DOC'

DX:
  - 'DEV'

enhancement:
  - 'ENH'

maintenance:
  - '(MAINT|TST)'

query:
  - '(Q|q)uery'

RFC:
  - 'RFC'
