bug:
  - changed-files:
      - any-glob-to-any-file:
          - "pecon/**"
          - "tests/**"

feature:
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**"
          - "docs/**"

doc:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"

chore:
  - changed-files:
      - any-glob-to-any-file:
          - "*.yml"
          - "*.md"
          - ".github/**"
