# .github/labeler.yml
# PR labeler for pecon organization
bug:
  - "pecon/**"
  - "tests/**"
feature:
  - "examples/**"
  - "docs/**"
doc:
  - "docs/**"
chore:
  - "*.yml"
  - "*.md"
  - ".github/**"

