# CORRECT v5 syntax - each label needs "any", "all", or "changed-files" array
"test-label":
  - any: ["**"]  # This will match ANY file

"documentation":
  - any: ["**"]  # Will label ALL PRs as documentation

"bug":
  - any: ["**"]  # Will also label ALL PRs as bug
