name: Bug Report
description: Report a bug or unexpected behavior
title: "BUG:"
labels: bug


body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a bug report.
  - type: markdown
    attributes:
        value: Before continuing, please check if there is similar issue.
  - type: textarea
    attributes:
      label: Describe your issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducing Code Example
      description: 'Paste the Reproducing code example and it will be rendered as a code block.'
      render: python
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error message
      description: 'Paste the *full* error message'
      render: shell
    validations:
      required: true
  - type: textarea
    attributes:
      label: Pecon/Python version
      render: shell
    validations:
      required: true
